"""tip e message_log

Revision ID: ee6362b387bd
Revises: 
Create Date: 2026-08-21 21:05:52.288959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee6362b387bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('event', sa.String(length=255), nullable=True),
    sa.Column('market', sa.String(length=255), nullable=True),
    sa.Column('odd', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('stake', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_image_ref', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('pending', 'green', 'red', 'void', name='tip_status'), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_needs_review'), 'tip', ['needs_review'], unique=False)
    op.create_index(op.f('ix_tip_status'), 'tip', ['status'], unique=False)
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tip_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('telegram', 'whatsapp', name='message_channel'), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', name='message_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tip_id'], ['tip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_log_tip_channel', 'message_log', ['tip_id', 'channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_log_tip_channel', table_name='message_log')
    op.drop_table('message_log')
    op.drop_index(op.f('ix_tip_status'), table_name='tip')
    op.drop_index(op.f('ix_tip_needs_review'), table_name='tip')
    op.drop_table('tip')
    # ### end Alembic commands ###

    # O autogenerate não remove os ENUM do Postgres; sem isso um upgrade
    # posterior falha com "type already exists".
    bind = op.get_bind()
    for enum_name in ('message_status', 'message_channel', 'tip_status'):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
